### ISSUE TITLE
TypeError: a.swap is not a function in form-validation.js:1:5199 w/ jQuery 1.12.0

### ISSUE THREAD

**Issue by AMA3** [aFarkas/webshim#560]
Hi Alex,

When using the latest Webshim w/ the latest released jQuery 1.12.0, I get:

TypeError: a.swap is not a function

in form-validation.js line 1 char 5199.

This happens when I click on a field with type="month" or type="date" in Firefox 43.0.4 after initializing Webshim with:

```
        webshim.setOptions('extendNative',true);
        webshim.polyfill('forms forms-ext');
```

The problem does not occur if I revert to jQuery 1.11.3.

I believe the issue is caused by this "fix" in jQuery 1.12:

https://github.com/jquery/jquery/commit/0019a463bdcb81dc6ba3434505a45774ca27f363

Thank you!

**Comment by sulibautista** [comment]
+1, I can reproduce this with the same configuration in Chrome 47

**Comment by tomascassidy** [comment]
Looks like webshim is using an undocumented internal API function.

https://github.com/jquery/jquery/issues/2058
https://github.com/jquery/jquery/commit/02a9d9f94b623ea8664b7b39fd57feb7de6c6a14
https://github.com/jquery/jquery/pull/2182

**Comment by marvinrabe** [comment]
Same issue here with Safari 9.0.3. Error is also occuring with the current jQuery2 version (2.2). Its working fine with jQuery 2.1

**Comment by philayres** [comment]
I ran across this issue after a Rails app was upgraded last week to address CVEs in a set of standard Gems. The packaged JQuery must have been bumped, which led to this function being hidden from the published API.

For anybody needing a short term fix, I was able to regain the functionality by extracting the original JQuery code for .swap:

   
```
 jQuery.swap = function( elem, options, callback, args ) {
    var ret, name, old = {};
    // Remember the old values, and insert the new ones
    for ( name in options ) {
            old[ name ] = elem.style[ name ];
            elem.style[ name ] = options[ name ];
    }

    ret = callback.apply( elem, args || [] );

    // Revert the old values
    for ( name in options ) {
            elem.style[ name ] = old[ name ];
    }
    return ret;
};

```
Not a long term fix, but maybe useful for others who suddenly have broken Rails apps.

**Comment by brucek2** [comment]
+1

**Comment by kattunga** [comment]
Hi philayres, can you explain me where to declare swap function?
I try to define in a js file that I included before polyfiller.js but it does'work.

**Comment by PRISMAY** [comment]
Same problem in IE11.  Project using jQuery 2.2.1 and webshims 1.15.10.

**Comment by jvanalst** [comment]
+1. Switching to jQuery 1.11.3 fixed the error.

**Comment by david-blacnet** [comment]
Hi, this is my first post in GitHub.

I've encountered this issue using jQuery 3.x and I've found that webshims still only works with jQuery 1.8, after I've added jQuery-migrate the problem is fixed.

**Comment by HenriPodolski** [comment]
You can just add the swap method: http://james.padolsey.com/jquery/#v=1.11.2&fn=jQuery.swap to  your code to make this work. It has no other dependencies. 

```js
$.swap = function (elem, options, callback, args) {
    var ret, name, old = {};

    // Remember the old values, and insert the new ones
    for (name in options) {
        old[name] = elem.style[name];
        elem.style[name] = options[name];
    }

    ret = callback.apply(elem, args || []);

    // Revert the old values
    for (name in options) {
        elem.style[name] = old[name];
    }

    return ret;
}
```

**Comment by jab** [comment]
After upgrading to 1.16.0 I was still able to reproduce this sometimes in Safari. Since this is the only thing I was using webshims for, I decided to ditch webshims in favor of a few lines of js based on http://codepen.io/ngault/pen/PqmyQE, and that's working better for me. (Now I'm free to upgrade to jQuery 3 too.) In case this helps anyone else here.
